services:
  postgres:
    image: postgres:15-alpine
    container_name: plakahub-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: plakahub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - plakahub_pgdata:/var/lib/postgresql/data

volumes:
  plakahub_pgdata:
